import React from 'react';
import {AbsoluteFill, Html5Audio, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {AUDIO, TIMING} from './config';
import {ensureFonts} from './fonts';
import {EASE, tween} from './lib/motion';
import {Grain, Vignette} from './components/Finish';
import {SceneCalendar} from './scenes/calendar/SceneCalendar';
import {SceneStreet} from './scenes/street/SceneStreet';
import {EndCard} from './scenes/endcard/EndCard';
import {C} from './theme';

ensureFonts();

/** Soft cut: the incoming scene fades up over the outgoing one. */
const FadeIn: React.FC<{frames: number; children: React.ReactNode}> = ({frames, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{opacity: tween(frame, 0, frames, [0, 1], EASE.inOut)}}>{children}</AbsoluteFill>;
};

export const CelinAd: React.FC = () => {
  const half = TIMING.crossfade / 2;
  const streetFrom = TIMING.street.start - half;
  return (
    <AbsoluteFill style={{backgroundColor: C.offWhite}}>
      <Sequence from={0} durationInFrames={TIMING.scene1.end + half} name="Scene 1 · Calendar">
        <SceneCalendar />
      </Sequence>
      <Sequence from={streetFrom} durationInFrames={TIMING.endCard - streetFrom} name="Scenes 2-3 · Street">
        <FadeIn frames={TIMING.crossfade}>
          <SceneStreet />
        </FadeIn>
      </Sequence>
      <Sequence from={TIMING.endCard} durationInFrames={450 - TIMING.endCard} name="End card">
        <EndCard />
      </Sequence>
      <Grain />
      <Vignette />
      {/* ambient pad + chime, generated by scripts/generate-audio.mjs */}
      <Html5Audio src={staticFile(AUDIO.file)} volume={AUDIO.volume} />
    </AbsoluteFill>
  );
};
